# specific path build
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure-terraform

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  artifact_name: sources_directory
  working_directory: $(Agent.BuildDirectory)/${{ variables.artifact_name }}
  project_name: estfdemo

stages:
  - stage: Build
    jobs:
    - job: publish
      displayName: Publish source directory
      steps:
      - publish: $(Build.SourcesDirectory)/azure-terraform
        artifact: sources_directory
        displayName: Publish source directory

  - template: release-stage.yml
    parameters:
      project_name: ${{ variables.project_name }}
      environment: dev
      service_connection: 'DevTestServiceConnection'
      working_directory: $(working_directory)